### PR TITLE
[docs] sphinx multiversion

### PR DESCRIPTION
**Pull request by Quandevla**
## Notes

- you can now close https://github.com/Quandela/Perceval/pull/281

You can remove tags we don't want with the regex `smv_tag_whitelist` like

```python
smv_tag_whitelist = r'^(?!(v0\.9\.3)|(v0\.9\.1))v\d+\.\d+\.\d+$'
```

To test which version sphinx is goinf to build you can do

```
cd docs && python -m sphinx_multiversion --dump-metadata source build/html
```

### CODE REVIEW

**Comment by Quandevla** [comment]
To test this PR you can do

```
cd docs
make multiversion
cd build/html
python -m http.server
# go to webpage
```

**Comment by Quandevla** [comment]
Note that we also can deploy the docs to github page with github actions ;)

**Review by MarionQuandela — CHANGES_REQUESTED** [review]
So first congrats the multi version works, but not as is (the index main page try to redirect to v0.10.0.post14 that doesn't exists). But once we are into a version we can go from version to version. Then we don't need *all* doc I think, can we have a list of tags either we exclude or include in our doc generation ?

**Comment by Quandevla** [comment]
I fix I have fixed the problem with redirection.

As explained, we can withelist versions (and kinda blacklist them)

```py
smv_tag_whitelist = r'^(?!(v0\.9\.3)|(v0\.9\.1))v\d+\.\d+\.\d+$'
```

Concerning the size, I think 50% of the generated docs are doctree files which are not useful for HTML (if I'm correct)


I also think that if you want to build the docs locally, we can use the `make html`

The `make multiversion` would be used only for automatic docs deployement with pipelines

**Pull request merged**
